apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-admin
rules:
- apiGroups: [""]
  resources: ["Secrets", "ClusterRoles", "Roles", "RoleBindings", "ClusterRoleBindings"]
  verbs: ["*"]